name: Deploy CloudFormation Stacks

on:
  workflow_dispatch:
    inputs:
      stackName:
        description: "The cloudformation using this stack name"
        required: true

jobs:
  cfn-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::331952164793:oidc-provider/token.actions.githubusercontent.com
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
          
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity
          aws-region: us-east-1

      - name: Deploy S3 Buckets CloudFormation Stacks
        run: |
          aws cloudformation deploy \
            --template-file ccinboxnx-s3-cloudfront-cloudformation.yml \
            --parameter-overrides file://s3andcloudfrontparameter.yml \
            --stack-name ${{ github.event.inputs.stackName }}
