name: Deploy CloudFormation Stacks

on:
  workflow_dispatch:
    inputs:
      stackName:
        description: "The cloudformation using this stack name"
        required: true
      cloudfromationTemplate:
        description: "file name of the cloudformation template"  
        required: true
      paramterfile:
        description: "paramter file name of the cloudformation template"
permissions:
      id-token: write   
      contents: read        

jobs:
  cfn-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::331952164793:role/githubaction
          role-session-name: OIDC_session
          aws-region: us-east-1

      - name: Deploy S3 Buckets CloudFormation Stacks
        run: |
          aws cloudformation deploy \
            --template-file ${{github.event.inputs.cloudfromationTemplate}} \
            --parameter-overrides file://${{github.event.inputs.paramterfile}} \
            --stack-name ${{ github.event.inputs.stackName }}
