name: Deploy CloudFormation Stacks

on:
  workflow_dispatch:
    inputs:
      stackName:
        description: "The cloudformation using this stack name"
        required: true

jobs:
  cfn-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy S3 Buckets CloudFormation Stacks
        run: |
          aws cloudformation deploy \
            --template-file ccinboxnx-s3-cloudfront-cloudformation.yml \
            --parameter-overrides file://s3andcloudfrontparameter.yml \
            --stack-name ${{ github.event.inputs.stackName }}
